version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: eslint
        versions: ["9"]
      - dependency-name: react
        versions: ["19"]
    groups:
      deps:
        dependency-type: "production"
      deps-dev:
        dependency-type: "development"