import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button, Navbar, ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { Nav } from "@/components/nav";
import { Foot } from "@/components/foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <Nav />
        <main className="dark:bg-gray-800">{children}</main>
        <div className="flex min-h-screen " />
        <Foot />
      </body>
    </html>
  );
}
